name: test
on:
  pull_request:
    branches:
      - main
      - dev
      - hotfix/**
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.X]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install npm
        run: npm ci
      - name: install firebase-tools
        run: npm i -g firebase-tools
      - name: run firebase emulator
        run: npm run emulators:test & sleep 10
      - name: test
        run: npm test
      - name: wait for emulator report
        run: sleep 10
      - name: coverage request
        id: coverageRequest
        uses: SonicGarden/firestore-rules-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report-url: "http://localhost:8080/emulator/v1/projects/oichan-testable-firebase:ruleCoverage"
